// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Invoice struct {
	ID        string
	OwnerID   string
	Title     string
	Body      string
	CreatedAt int64
	UpdatedAt int64
}
