// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices
WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, owner_id, title, body, created_at, updated_at FROM invoices
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :exec
INSERT INTO invoices (id, owner_id, title, body, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertInvoiceParams struct {
	ID        string
	OwnerID   string
	Title     string
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, insertInvoice,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listInvoicesByOwner = `-- name: ListInvoicesByOwner :many
SELECT id, owner_id, title, body, created_at, updated_at FROM invoices
WHERE owner_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListInvoicesByOwner(ctx context.Context, ownerID string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :exec
UPDATE invoices
SET title = ?, body = ?, updated_at = ?
WHERE id = ?
`

type UpdateInvoiceParams struct {
	Title     string
	Body      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoice,
		arg.Title,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
